INSERT INTO masterdata_districts (title, title_en, province_id) VALUES
('พระนคร', 'Phra Nakhon', 1),
('ดุสิต', 'Dusit', 1),
('หนองจอก', 'Nong Chok', 1),
('บางรัก', 'Bang Rak', 1),
('บางเขน', 'Bang Khen', 1),
('บางกะปิ', 'Bang Kapi', 1),
('ปทุมวัน', 'Pathum Wan', 1),
('ป้อมปราบศัตรูพ่าย', 'Pom Prap Sattruphai', 1),
('พระโขนง', 'Phra Khanong', 1),
('มีนบุรี', 'Min Buri', 1),
('ลาดกระบัง', 'Lat Krabang', 1),
('ยานนาวา', 'Yannawa', 1),
('สัมพันธวงศ์', 'Samphanthawong', 1),
('พญาไท', 'Phaya Thai', 1),
('ธนบุรี', 'Thon Buri', 1),
('บางกอกใหญ่', 'Bangkok Yai', 1),
('ห้วยขวาง', 'Huai Khwang', 1),
('คลองสาน', 'Khlong San', 1),
('ตลิ่งชัน', 'Taling Chan', 1),
('บางกอกน้อย', 'Bangkok Noi', 1),
('บางขุนเทียน', 'Bang Khun Thian', 1),
('ภาษีเจริญ', 'Phasi Charoen', 1),
('หนองแขม', 'Nong Khaem', 1),
('ราษฎร์บูรณะ', 'Rat Burana', 1),
('บางพลัด', 'Bang Phlat', 1),
('ดินแดง', 'Din Daeng', 1),
('บึงกุ่ม', 'Bung Kum', 1),
('สาทร', 'Sa Thon', 1),
('บางซื่อ', 'Bang Su', 1),
('จตุจักร', 'Chatuchak', 1),
('บางคอแหลม', 'Bang Kho Laem', 1),
('ประเวศ', 'Prawet', 1),
('คลองเตย', 'Khlong Toei', 1),
('สวนหลวง', 'Suan Luang', 1),
('จอมทอง', 'Chom Thong', 1),
('ดอนเมือง', 'Don Mueang', 1),
('ราชเทวี', 'Rat Thewi', 1),
('ลาดพร้าว', 'Lat Phrao', 1),
('วัฒนา', 'Watthana', 1),
('บางแค', 'Bang Khae', 1),
('หลักสี่', 'Lak Si', 1),
('สายไหม', 'Sai Mai', 1),
('คันนายาว', 'Khanna Yao', 1),
('สะพานสูง', 'Saphan Sung', 1),
('วังทองหลาง', 'Wang Thong Lang', 1),
('คลองสามวา', 'Khlong Sam Wa', 1),
('บางนา', 'Bang Na', 1),
('ทวีวัฒนา', 'Thawi Watthana', 1),
('ทุ่งครุ', 'Thung Khu', 1),
('บางบอน', 'Bang Bon', 1),
('เมืองสมุทรปราการ', 'Mueang Samut Prakan', 2),
('บางบ่อ', 'Bang Bo', 2),
('บางพลี', 'Bang Phli', 2),
('พระประแดง', 'Phra Pradaeng', 2),
('พระสมุทรเจดีย์', 'Phra Samut Chedi', 2),
('บางเสาธง', 'Bang Sao Thong', 2),
('เมืองนนทบุรี', 'Mueang Nonthaburi', 3),
('บางกรวย', 'Bang Kruai', 3),
('บางใหญ่', 'Bang Yai', 3),
('บางบัวทอง', 'Bang Bua Thong', 3),
('ไทรน้อย', 'Sai Noi', 3),
('ปากเกร็ด', 'Pak Kret', 3),
('เมืองปทุมธานี', 'Mueang Pathum Thani', 4),
('คลองหลวง', 'khlong Luang', 4),
('ธัญบุรี', 'Thanyaburi', 4),
('หนองเสือ', 'Nong Suea', 4),
('ลาดหลุมแก้ว', 'Lat Lum Kaeo', 4),
('ลำลูกกา', 'Lam Luk Ka', 4),
('สามโคก', 'Sam Khok', 4),
('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 5),
('ท่าเรือ', 'Tha Ruea', 5),
('นครหลวง', 'Nakhon Luang', 5),
('บางไทร', 'Bang Sai', 5),
('บางบาล', 'Bang Ban', 5),
('บางปะอิน', 'Bang Pa-in', 5),
('บางปะหัน', 'Bang Pahan', 5),
('ผักไห่', 'Phak Hai', 5),
('ภาชี', 'Phachi', 5),
('ลาดบัวหลวง', 'Lat Bua Luang', 5),
('วังน้อย', 'Wang Noi', 5),
('เสนา', 'Sena', 5),
('บางซ้าย', 'Bang Sai', 5),
('อุทัย', 'Uthai', 5),
('มหาราช', 'Maha Rat', 5),
('บ้านแพรก', 'Ban Phraek', 5),
('เมืองอ่างทอง', 'Mueang Ang Thong', 6),
('ไชโย', 'Chaiyo', 6),
('ป่าโมก', 'Pa Mok', 6),
('โพธิ์ทอง', 'Pho Thong', 6),
('แสวงหา', 'Sawaeng Ha', 6),
('วิเศษชัยชาญ', 'Wiset Chai Chan', 6),
('สามโก้', 'Samko', 6),
('เมืองลพบุรี', 'Mueang Lop Buri', 7),
('พัฒนานิคม', 'Phatthana Nikhom', 7),
('โคกสำโรง', 'Khok Samrong', 7),
('ชัยบาดาล', 'Chai Badan', 7),
('ท่าวุ้ง', 'Tha Wung', 7),
('บ้านหมี่', 'Ban Mi', 7),
('ท่าหลวง', 'Tha Luang', 7),
('สระโบสถ์', 'Sa Bot', 7),
('โคกเจริญ', 'Khok Charoen', 7),
('ลำสนธิ', 'Lam Sonthi', 7),
('หนองม่วง', 'Nong Muang', 7),
('เมืองสิงห์บุรี', 'Mueang Sing Buri', 8),
('บางระจัน', 'Bang Rachan', 8),
('ค่ายบางระจัน', 'Khai Bang Rachan', 8),
('พรหมบุรี', 'Phrom Buri', 8),
('ท่าช้าง', 'Tha Chang', 8),
('อินทร์บุรี', 'In Buri', 8),
('เมืองชัยนาท', 'Mueang Chai Nat', 9),
('มโนรมย์', 'Manorom', 9),
('วัดสิงห์', 'Wat Sing', 9),
('สรรพยา', 'Sapphaya', 9),
('สรรคบุรี', 'Sankhaburi', 9),
('หันคา', 'Hankha', 9),
('หนองมะโมง', 'Nong Mamong', 9),
('เนินขาม', 'Noen Kham', 9),
('เมืองสระบุรี', 'Mueang Saraburi', 10),
('แก่งคอย', 'Kaeng Khoi', 10),
('หนองแค', 'Nong Khae', 10),
('วิหารแดง', 'Wihan Daeng', 10),
('หนองแซง', 'Nong Saeng', 10),
('บ้านหมอ', 'Ban Mo', 10),
('ดอนพุด', 'Don Phut', 10),
('หนองโดน', 'Nong Don', 10),
('พระพุทธบาท', 'Phra Phutthabat', 10),
('เสาไห้', 'Sao Hai', 10),
('มวกเหล็ก', 'Muak Lek', 10),
('วังม่วง', 'Wang Muang', 10),
('เฉลิมพระเกียรติ', 'Chaloem Phra Kiet', 10),
('เมืองชลบุรี', 'Mueang Chon Buri', 11),
('บ้านบึง', 'Ban Bueng', 11),
('หนองใหญ่', 'Nong Yai', 11),
('บางละมุง', 'Bang Lamung', 11),
('พานทอง', 'Phan Thong', 11),
('พนัสนิคม', 'Phanat Nikhom', 11),
('ศรีราชา', 'Si Racha', 11),
('เกาะสีชัง', 'Ko Sichang', 11),
('สัตหีบ', 'Sattahip', 11),
('บ่อทอง', 'Bo Thong', 11),
('เกาะจันทร์', 'Ko Chan', 11),
('เมืองระยอง', 'Mueang Rayong', 12),
('บ้านฉาง', 'Ban Chang', 12),
('แกลง', 'Klaeng', 12),
('วังจันทร์', 'Wang Chan', 12),
('บ้านค่าย', 'Ban Khai', 12),
('ปลวกแดง', 'Pluak Daeng', 12),
('เขาชะเมา', 'Khao Chamao', 12),
('นิคมพัฒนา', 'Nikhom Phatthana', 12),
('เมืองจันทบุรี', 'Mueang Chanthaburi', 13),
('ขลุง', 'Khlung', 13),
('ท่าใหม่', 'Tha Mai', 13),
('โป่งน้ำร้อน', 'Pong Nam Ron', 13),
('มะขาม', 'Makham', 13),
('แหลมสิงห์', 'Laem Sing', 13),
('สอยดาว', 'Soi Dao', 13),
('แก่งหางแมว', 'Kaeng Hang Maeo', 13),
('นายายอาม', 'Na Yai Am', 13),
('เขาคิชฌกูฏ', 'Khao Khitchakut', 13),
('เมืองตราด', 'Mueang Trat', 14),
('คลองใหญ่', 'Khlong Yai', 14),
('เขาสมิง', 'Khao Saming', 14),
('บ่อไร่', 'Bo Rai', 14),
('แหลมงอบ', 'Laem Ngop', 14),
('เกาะกูด', 'Ko Kut', 14),
('เกาะช้าง', 'Ko Chang', 14),
('เมืองฉะเชิงเทรา', 'Mueang Chachoengsao', 15),
('บางคล้า', 'Bang Khla', 15),
('บางน้ำเปรี้ยว', 'Bang Nam Priao', 15),
('บางปะกง', 'Bang Pakong', 15),
('บ้านโพธิ์', 'Ban Pho', 15),
('พนมสารคาม', 'Phanom Sarakham', 15),
('ราชสาส์น', 'Ratchasan', 15),
('สนามชัยเขต', 'Sanam Chai Khet', 15),
('แปลงยาว', 'Pleang Yao', 15),
('ท่าตะเกียบ', 'Tha Takiap', 15),
('คลองเขื่อน', 'Khlong Khuean', 15),
('เมืองปราจีนบุรี', 'Mueang Prachin Buri', 16),
('กบินทร์บุรี', 'Kabin Buri', 16),
('นาดี', 'Na Di', 16),
('บ้านสร้าง', 'Ban Sang', 16),
('ประจันตคาม', 'Prachantakham', 16),
('ศรีมหาโพธิ', 'Si Maha Phot', 16),
('ศรีมโหสถ', 'Si Mahosot', 16),
('เมืองนครนายก', 'Mueang Nakhon Nayok', 17),
('ปากพลี', 'Pak Phli', 17),
('บ้านนา', 'Ban Na', 17),
('องครักษ์', 'Ongkharak', 17),
('เมืองสระแก้ว', 'Mueang Sa Kaeo', 18),
('คลองหาด', 'Khlong Hat', 18),
('ตาพระยา', 'Ta Phraya', 18),
('วังน้ำเย็น', 'Wang Nam Yen', 18),
('วัฒนานคร', 'Watthana Nakhon', 18),
('อรัญประเทศ', 'Aranyaprathet', 18),
('เขาฉกรรจ์', 'Khao Chakan', 18),
('โคกสูง', 'Khok Sung', 18),
('วังสมบูรณ์', 'Wang Sombun', 18),
('เมืองนครราชสีมา', 'Mueang Nakhon Ratchasima', 19),
('ครบุรี', 'Khon Buri', 19),
('เสิงสาง', 'Soeng Sang', 19),
('คง', 'Khong', 19),
('บ้านเหลื่อม', 'Ban Lueam', 19),
('จักราช', 'Chakkarat', 19),
('โชคชัย', 'Chok Chai', 19),
('ด่านขุนทด', 'Dan Khun Thot', 19),
('โนนไทย', 'Non Thai', 19),
('โนนสูง', 'Non Sung', 19),
('ขามสะแกแสง', 'Kham Sakaesaeng', 19),
('บัวใหญ่', 'Bua Yai', 19),
('ประทาย', 'Prathai', 19),
('ปักธงชัย', 'Pak Thong Chai', 19),
('พิมาย', 'Phimai', 19),
('ห้วยแถลง', 'Huai Thalaeng', 19),
('ชุมพวง', 'Chum Phuang', 19),
('สูงเนิน', 'Sung Noen', 19),
('ขามทะเลสอ', 'Kham Thale So', 19),
('สีคิ้ว', 'Si Khio', 19),
('ปากช่อง', 'Pak Chong', 19),
('หนองบุญมาก', 'Nong Bunmak', 19),
('แก้งสนามนาง', 'Kaeng Sanam Nang', 19),
('โนนแดง', 'Non Daeng', 19),
('วังน้ำเขียว', 'Wang Nam Khiao', 19),
('เทพารักษ์', 'Thepharak', 19),
('เมืองยาง', 'Mueang Yang', 19),
('พระทองคำ', 'Phra Thong Kham', 19),
('ลำทะเมนชัย', 'Lamtaman Chai', 19),
('บัวลาย', 'Bua Lai', 19),
('สีดา', 'Sida', 19),
('เฉลิมพระเกียรติ', 'Chaloem Phra Kiet', 19),
('เมืองบุรีรัมย์', 'Mueang Buri Ram', 20),
('คูเมือง', 'Khu Mueang', 20),
('กระสัง', 'Krasang', 20),
('นางรอง', 'Nang Rong', 20),
('หนองกี่', 'Nong Ki', 20),
('ละหานทราย', 'Lahan Sai', 20),
('ประโคนชัย', 'Prakhon Chai', 20),
('บ้านกรวด', 'Ban Kruat', 20),
('พุทไธสง', 'Phutthaisong', 20),
('ลำปลายมาศ', 'Lam Plai Mat', 20),
('สตึก', 'Satuek', 20),
('ปะคำ', 'Pakham', 20),
('นาโพธิ์', 'Na Pho', 20),
('หนองหงส์', 'Nong Hong', 20),
('พลับพลาชัย', 'Phlapphla Chai', 20),
('ห้วยราช', 'Huai Rat', 20),
('โนนสุวรรณ', 'Non Din Daeng', 20),
('ชำนิ', 'Chamni', 20),
('บ้านใหม่ไชยพจน์', 'Ban Mai Chaiyaphot', 20),
('โนนดินแดง', 'Non Din Daeng', 20),
('บ้านด่าน', 'Ban Dan', 20),
('แคนดง', 'Khaen Dong', 20),
('เฉลิมพระเกียรติ', 'Chaloem Phra Kiet', 20),
('เมืองสุรินทร์', 'Mueang Surin', 21),
('ชุมพลบุรี', 'Chumphon Buri', 21),
('ท่าตูม', 'Tha Tum', 21),
('จอมพระ', 'Chom Phra', 21),
('ปราสาท', 'Prasat', 21),
('กาบเชิง', 'Kap Choeng', 21),
('รัตนบุรี', 'Rattanaburi', 21),
('สนม', 'Sanom', 21),
('ศีขรภูมิ', 'Sikhoraphum', 21),
('สังขะ', 'Sangkha', 21),
('ลำดวน', 'Lamduan', 21),
('สำโรงทาบ', 'Samrong Thap', 21),
('บัวเชด', 'Buachet', 21),
('พนมดงรัก', 'Phanom Dong Rak', 21),
('ศรีณรงค์', 'Si Narong', 21),
('เขวาสินรินทร์', 'Khwao Sinarin', 21),
('โนนนารายณ์', 'Non Narai', 21),
('เมืองศรีสะเกษ', 'Mueang Si Sa Ket', 22),
('ยางชุมน้อย', 'Yang Chum Noi', 22),
('กันทรารมย์', 'Kanthararom', 22),
('กันทรลักษ์', 'Kantharalak', 22),
('ขุขันธ์', 'Khukhan', 22),
('ไพรบึง', 'Phrai Bueng', 22),
('ปรางค์กู่', 'Prang Ku', 22),
('ขุนหาญ', 'Khun Han', 22),
('ราษีไศล', 'Rasi Salai', 22),
('อุทุมพรพิสัย', 'Uthumphon Phisai', 22),
('บึงบูรพ์', 'Bueng Bun', 22),
('ห้วยทับทัน', 'Huai Thap Than', 22),
('โนนคูณ', 'Non Khun', 22),
('ศรีรัตนะ', 'Si Rattana', 22),
('น้ำเกลี้ยง', 'Nam Kliang', 22),
('วังหิน', 'Wang Hin', 22),
('ภูสิงห์', 'Phu Sing', 22),
('เมืองจันทร์', 'Mueang Chan', 22),
('เบญจลักษ์', 'Benchalak', 22),
('พยุห์', 'Phayu', 22),
('โพธิ์ศรีสุวรรณ', 'Pho Si Suwan', 22),
('ศิลาลาด', 'Sila Lat', 22),
('เมืองอุบลราชธานี', 'Mueang Ubon Ratchathani', 23),
('ศรีเมืองใหม่', 'Si Mueang Mai', 23),
('โขงเจียม', 'Khong Chiam', 23),
('เขื่องใน', 'Khueang Nai', 23),
('เขมราฐ', 'Khemarat', 23),
('เดชอุดม', 'Det Udom', 23),
('นาจะหลวย', 'Na Chaluai', 23),
('น้ำยืน', 'Nam Yuen', 23),
('บุณฑริก', 'Boontharik', 23),
('ตระการพืชผล', 'Trakan Phuet Phon', 23),
('กุดข้าวปุ้น', 'Kut Khaopun', 23),
('ม่วงสามสิบ', 'Muang Sam Sip', 23),
('วารินชำราบ', 'Warin Chamrap', 23),
('พิบูลมังสาหาร', 'Phibun Mangsahan', 23),
('ตาลสุม', 'Tan Sum', 23),
('โพธิ์ไทร', 'Pho Sai', 23),
('สำโรง', 'Samrong', 23),
('ดอนมดแดง', 'Don Mot Daeng', 23),
('สิรินธร', 'Sirindhorn', 23),
('ทุ่งศรีอุดม', 'Thung Si Udom', 23),
('นาเยีย', 'Na Yia', 23),
('นาตาล', 'Na Tan', 23),
('เหล่าเสือโก้ก', 'Lao Suea Kok', 23),
('สว่างวีระวงศ์', 'Sawang Wirawong', 23),
('น้ำขุ่น', 'Nam Khun', 23),
('เมืองยโสธร', 'Mueang Yasothon', 24),
('ทรายมูล', 'Sai Mun', 24),
('กุดชุม', 'Kut Chum', 24),
('คำเขื่อนแก้ว', 'Kham Khuean Kaeo', 24),
('ป่าติ้ว', 'Pa Tio', 24),
('มหาชนะชัย', 'Maha Chana Chai', 24),
('ค้อวัง', 'Kho Wang', 24),
('เลิงนกทา', 'Loeng Nok Tha', 24),
('ไทยเจริญ', 'Thai Charoen', 24),
('เมืองชัยภูมิ', 'Mueang Chaiyaphum', 25),
('บ้านเขว้า', 'Ban Khwao', 25),
('คอนสวรรค์', 'Khon Sawan', 25),
('เกษตรสมบูรณ์', 'Kaset Sombun', 25),
('หนองบัวแดง', 'Nong Bua Daeng', 25),
('จัตุรัส', 'Chatturat', 25),
('บำเหน็จณรงค์', 'Bamnet Narong', 25),
('หนองบัวระเหว', 'Nong Bua Rawe', 25),
('เทพสถิต', 'Thep Sathit', 25),
('ภูเขียว', 'Phu Khiao', 25),
('บ้านแท่น', 'Ban Thaen', 25),
('แก้งคร้อ', 'Kaeng Khro', 25),
('คอนสาร', 'Khon San', 25),
('ภักดีชุมพล', 'Phakdi Chumphon', 25),
('เนินสง่า', 'Noen Sa-nga', 25),
('ซับใหญ่', 'Sap Yai', 25),
('เมืองอำนาจเจริญ', 'Mueang Amnat Charoen', 26),
('ชานุมาน', 'Chanuman', 26),
('ปทุมราชวงศา', 'Pathum Ratchawongsa', 26),
('พนา', 'Phana', 26),
('เสนางคนิคม', 'Senangkhanikhom', 26),
('หัวตะพาน', 'Hua Taphan', 26),
('ลืออำนาจ', 'Lue Amnat', 26),
('บึงกาฬ', 'Bueng Kan', 27),
('พรเจริญ', 'Phon Charoen', 27),
('โซ่พิสัย', 'So Phisai', 27),
('เซกา', 'Seka', 27),
('ปากคาด', 'Pak Khat', 27),
('บึงโขงหลง', 'Bueng Khong Long', 27),
('ศรีวิไล', 'Si Wilai', 27),
('บุ่งคล้า', 'Bung Khla', 27),
('เมืองหนองบัวลำภู', 'Mueang Nong Bua Lam Phu', 28),
('นากลาง', 'Na Klang', 28),
('โนนสัง', 'Non Sang', 28),
('ศรีบุญเรือง', 'Si Bun Rueang', 28),
('สุวรรณคูหา', 'Suwannakhuha', 28),
('นาวัง', 'Na Wang', 28),
('เมืองขอนแก่น', 'Mueang Khon Kaen', 29),
('บ้านฝาง', 'Ban Fang', 29),
('พระยืน', 'Phra Yuen', 29),
('หนองเรือ', 'Nong Ruea', 29),
('ชุมแพ', 'Chum Phae', 29),
('สีชมพู', 'Si Chomphu', 29),
('น้ำพอง', 'Nam Phong', 29),
('อุบลรัตน์', 'Ubolratana', 29),
('กระนวน', 'Kranuan', 29),
('บ้านไผ่', 'Ban Phai', 29),
('เปือยน้อย', 'Pueai Noi', 29),
('พล', 'Phon', 29),
('แวงใหญ่', 'Waeng Yai', 29),
('แวงน้อย', 'Waeng Noi', 29),
('หนองสองห้อง', 'Nong Song Hong', 29),
('ภูเวียง', 'Phu Wiang', 29),
('มัญจาคีรี', 'Mancha Khiri', 29),
('ชนบท', 'Chonnabot', 29),
('เขาสวนกวาง', 'Khao Suan Kwang', 29),
('ภูผาม่าน', 'Phu Phaman', 29),
('ซำสูง', 'Sam Sung', 29),
('โคกโพธิ์ไชย', 'Khok Pho Chai', 29),
('หนองนาคำ', 'Nong Na Kham', 29),
('บ้านแฮด', 'Ban Haet', 29),
('โนนศิลา', 'Non Sila', 29),
('เวียงเก่า', 'Wiang Kao', 29),
('เมืองอุดรธานี', 'Mueang Udon Thani', 30),
('กุดจับ', 'Kut Chap', 30),
('หนองวัวซอ', 'Nong Wua So', 30),
('กุมภวาปี', 'Kumphawapi', 30),
('โนนสะอาด', 'Non Sa-at', 30),
('หนองหาน', 'Nong Saeng', 30),
('ทุ่งฝน', 'Thung Fon', 30),
('ไชยวาน', 'Chai Wan', 30),
('ศรีธาตุ', 'Si That', 30),
('วังสามหมอ', 'Wang Sam Mo', 30),
('บ้านดุง', 'Ban Dung', 30),
('บ้านผือ', 'Ban Phue', 30),
('น้ำโสม', 'Nam Som', 30),
('เพ็ญ', 'Phen', 30),
('สร้างคอม', 'Sang Khom', 30),
('หนองแสง', 'Nong Saeng', 30),
('นายูง', 'Na Yung', 30),
('พิบูลย์รักษ์', 'Phibun Rak', 30),
('กู่แก้ว', 'Ku Kaeo', 30),
('ประจักษ์ศิลปาคม', 'Prachaksinlapakhom', 30),
('เมืองเลย', 'Mueang Loei', 31),
('นาด้วง', 'Na Duang', 31),
('เชียงคาน', 'Chiang Khan', 31),
('ปากชม', 'Pak Chom', 31),
('ด่านซ้าย', 'Dan Sai', 31),
('นาแห้ว', 'Na Haeo', 31),
('ภูเรือ', 'Phu Ruea', 31),
('ท่าลี่', 'Tha Li', 31),
('วังสะพุง', 'Wang Saphung', 31),
('ภูกระดึง', 'Phu Kradueng', 31),
('ภูหลวง', 'Phu Luang', 31),
('ผาขาว', 'Pha  Khao', 31),
('เอราวัณ', 'Erawan', 31),
('หนองหิน', 'Nong Hin', 31),
('เมืองหนองคาย', 'Mueang Nong Khai', 32),
('ท่าบ่อ', 'Tha Bo', 32),
('โพนพิสัย', 'Phon Phisai', 32),
('ศรีเชียงใหม่', 'Si Chiang Mai', 32),
('สังคม', 'Sangkhom', 32),
('สระใคร', 'Sakhrai', 32),
('เฝ้าไร่', 'Fao Rai', 32),
('รัตนวาปี', 'Rattanawapi', 32),
('โพธิ์ตาก', 'Pho Tak', 32),
('เมืองมหาสารคาม', 'Mueang Maha Sarakham', 33),
('แกดำ', 'Kae Dam', 33),
('โกสุมพิสัย', 'Kosum Phisai', 33),
('กันทรวิชัย', 'Kantharawichai', 33),
('เชียงยืน', 'Chiang Yuen', 33),
('บรบือ', 'Borabue', 33),
('นาเชือก', 'Na Chueak', 33),
('พยัคฆภูมิพิสัย', 'Phayakkhaphum Phisai', 33),
('วาปีปทุม', 'Wapi Pathum', 33),
('นาดูน', 'Na Dun', 33),
('ยางสีสุราช', 'Yang Sisurat', 33),
('กุดรัง', 'Kut Rang', 33),
('ชื่นชม', 'Chuen Chom', 33),
('เมืองร้อยเอ็ด', 'Mueang Roi Et', 34),
('เกษตรวิสัย', 'Kaset Wisai', 34),
('ปทุมรัตต์', 'Pathum Rat', 34),
('จตุรพักตรพิมาน', 'Chaturaphak Phiman', 34),
('ธวัชบุรี', 'Thawat Buri', 34),
('พนมไพร', 'Phanom Phrai', 34),
('โพนทอง', 'Phon Thong', 34),
('โพธิ์ชัย', 'Pho Chai', 34),
('หนองพอก', 'Nong Phok', 34),
('เสลภูมิ', 'Selaphum', 34),
('สุวรรณภูมิ', 'Suwannaphum', 34),
('เมืองสรวง', 'Mueang Suang', 34),
('โพนทราย', 'Phon Sai', 34),
('อาจสามารถ', 'At Samat', 34),
('เมยวดี', 'Moei Wadi', 34),
('ศรีสมเด็จ', 'Si Somdet', 34),
('จังหาร', 'Changhan', 34),
('เชียงขวัญ', 'Chiang Khwan', 34),
('หนองฮี', 'Nong Hi', 34),
('ทุ่งเขาหลวง', 'Thung Khao Luang', 34),
('เมืองกาฬสินธุ์', 'Mueang Kalasin', 35),
('นามน', 'Na Mon', 35),
('กมลาไสย', 'Kamalasai', 35),
('ร่องคำ', 'Rong Kham', 35),
('กุฉินารายณ์', 'Kuchinarai', 35),
('เขาวง', 'Khao Wong', 35),
('ยางตลาด', 'Yang Talat', 35),
('ห้วยเม็ก', 'Huai Mek', 35),
('สหัสขันธ์', 'Sahatsakhan', 35),
('คำม่วง', 'Kham Muang', 35),
('ท่าคันโท', 'Tha Khantho', 35),
('หนองกุงศรี', 'Nong Kung Si', 35),
('สมเด็จ', 'Somdet', 35),
('ห้วยผึ้ง', 'Huai Phueng', 35),
('สามชัย', 'Sam Chai', 35),
('นาคู', 'Na Khu', 35),
('ดอนจาน', 'Don Chan', 35),
('ฆ้องชัย', 'Khong Chai', 35),
('เมืองสกลนคร', 'Mueang Sakon Nakhon', 36),
('กุสุมาลย์', 'Kusuman', 36),
('กุดบาก', 'Kut Bak', 36),
('พรรณานิคม', 'Phanna Nikhom', 36),
('พังโคน', 'Phanh khon', 36),
('วาริชภูมิ', 'Waritchaphum', 36),
('นิคมน้ำอูน', 'Nikhom Nam un', 36),
('วานรนิวาส', 'Wanon Niwat', 36),
('คำตากล้า', 'Kham Ta Kla', 36),
('บ้านม่วง', 'Ban Muang', 36),
('อากาศอำนวย', 'Akat Amnuai', 36),
('สว่างแดนดิน', 'Sawang Daen Din', 36),
('ส่องดาว', 'Song Dao', 36),
('เต่างอย', 'Tao Ngoi', 36),
('โคกศรีสุพรรณ', 'Khok Si Suphan', 36),
('เจริญศิลป์', 'Charoen Sin', 36),
('โพนนาแก้ว', 'Phon Na Kaeo', 36),
('ภูพาน', 'Phu Phan', 36),
('เมืองนครพนม', 'Mueang Nakhon Phanom', 37),
('ปลาปาก', 'Pla Pak', 37),
('ท่าอุเทน', 'Tha Uthen', 37),
('บ้านแพง', 'Ban Phaeng', 37),
('ธาตุพนม', 'That Phanom', 37),
('เรณูนคร', 'Renu Nakhon', 37),
('นาแก', 'Na Kae', 37),
('ศรีสงคราม', 'Si Songkhram', 37),
('นาหว้า', 'Na Wa', 37),
('โพนสวรรค์', 'Phon Sawan', 37),
('นาทม', 'Na Thom', 37),
('วังยาง', 'Wang Yang', 37),
('เมืองมุกดาหาร', 'Mueang Mukdahan', 38),
('นิคมคำสร้อย', 'Nikhom Kham Soi', 38),
('ดอนตาล', 'Don Tan', 38),
('ดงหลวง', 'Don Tan', 38),
('คำชะอี', 'Khamcha-i', 38),
('ว่านใหญ่', 'Wan Yai', 38),
('หนองสูง', 'Nong Sung', 38),
('เมืองเชียงใหม่', 'Mueang Chiang Mai', 39),
('จอมทอง', 'Chom Thong', 39),
('แม่แจ่ม', 'Mae Chaem', 39),
('เชียงดาว', 'Chiang Dao', 39),
('ดอยสะเก็ด', 'Doi Saket', 39),
('แม่แตง', 'Mae Taeng', 39),
('แม่ริม', 'Mae Rim', 39),
('สะเมิง', 'Samoeng', 39),
('ฝาง', 'Fang', 39),
('แม่อาย', 'Mae Ai', 39),
('พร้าว', 'Phrao', 39),
('สันป่าตอง', 'San Pa Tong', 39),
('สันกำแพง', 'San Kamphaeng', 39),
('สันทราย', 'San Sai', 39),
('หางดง', 'Hang Dong', 39),
('ฮอด', 'Hot', 39),
('ดอยเต่า', 'Doi Tao', 39),
('อมก๋อย', 'Omkoi', 39),
('สารภี', 'Saraphi', 39),
('เวียงแหง', 'Wiang Haeng', 39),
('ไชยปราการ', 'Chai Prakan', 39),
('แม่วาง', 'Mae Wang', 39),
('แม่ออน', 'Mae On', 39),
('ดอยหล่อ', 'Doi Lo', 39),
('กัลยาณิวัฒนา', 'Kanlayaniwatthana', 39),
('เมืองลำพูน', 'Mueang Lamphun', 40),
('แม่ทา', 'Mae Tha', 40),
('บ้านโฮ่ง', 'Ban Hong', 40),
('ลี้', 'Li', 40),
('ทุ่งหัวช้าง', 'Thung Hua Chang', 40),
('ป่าซาง', 'Pa Sang', 40),
('บ้านธิ', 'Ban Thi', 40),
('เวียงหนองล่อง', 'Wiang Nong Long', 40),
('เมืองลำปาง', 'Mueang Lampang', 41),
('แม่เมาะ', 'Mae Mo', 41),
('เกาะคา', 'Ko kha', 41),
('เสริมงาม', 'Soem Ngam', 41),
('งาว', 'Ngao', 41),
('แจ้ห่ม', 'Chae Hom', 41),
('วังเหนือ', 'Wang Nuea', 41),
('เถิน', 'Thoen', 41),
('แม่พริก', 'Mae Phrik', 41),
('แม่ทะ', 'Mae Tha', 41),
('สบปราบ', 'Sop Prap', 41),
('ห้างฉัตร', 'Hang Chat', 41),
('เมืองปาน', 'Mueang Pan', 41),
('เมืองอุตรดิตถ์', 'Mueang Uttaradit', 42),
('ตรอน', 'Tron', 42),
('ท่าปลา', 'Tha Pla', 42),
('น้ำปาด', 'Nam Pat', 42),
('ฟากท่า', 'Fak Tha', 42),
('บ้านโคก', 'Ban Khok', 42),
('พิชัย', 'Phichai', 42),
('ลับแล', 'Laplae', 42),
('ทองแสนขัน', 'Thong Saen Khan', 42),
('เมืองแพร่', 'Mueang Phrae', 43),
('ร้องกวาง', 'Mueang Phrae', 43),
('ลอง', 'Long', 43),
('สูงเม่น', 'Sung Men', 43),
('เด่นชัย', 'Den Chai', 43),
('สอง', 'Song', 43),
('วังชิ้น', 'Wang Chin', 43),
('หนองม่วงไข่', 'Nong Muang Khai', 43),
('เมืองน่าน', 'Mueang Nan', 44),
('แม่จริม', 'Mae Charim', 44),
('บ้านหลวง', 'Ban Luang', 44),
('นาน้อย', 'Na Noi', 44),
('ปัว', 'Pua', 44),
('ท่าวังผา', 'Tha Wang Pha', 44),
('เวียงสา', 'Wiang Sa', 44),
('ทุ่งช้าง', 'Thung Chang', 44),
('เชียงกลาง', 'Chiang Klang', 44),
('นาหมื่น', 'Na Muen', 44),
('สันติสุข', 'Santi Suk', 44),
('บ่อเกลือ', 'Bo Kluea', 44),
('สองแคว', 'Song Khwae', 44),
('ภูเพียง', 'Phu Phiang', 44),
('เฉลิมพระเกียรติ', 'Chaloem Phra Kiet', 44),
('เมืองพะเยา', 'Mueang Phayao', 45),
('จุน', 'Mueang Phayao', 45),
('เชียงคำ', 'Mueang Phayao', 45),
('เชียงม่วน', 'Mueang Phayao', 45),
('ดอกคำใต้', 'Mueang Phayao', 45),
('ปง', 'Mueang Phayao', 45),
('แม่ใจ', 'Mueang Phayao', 45),
('ภูซาง', 'Mueang Phayao', 45),
('ภูกามยาว', 'Mueang Phayao', 45),
('เมืองเชียงราย', 'Mueang Chiang Rai', 46),
('เวียงชัย', 'Wiang Chai', 46),
('เชียงของ', 'Chiang Khong', 46),
('เทิง', 'Thoeng', 46),
('พาน', 'Phan', 46),
('ป่าแดด', 'Pa Daet', 46),
('แม่จัน', 'Mae Chan', 46),
('เชียงแสน', 'Chiang Saen', 46),
('แม่สาย', 'Mae Sai', 46),
('แม่สรวย', 'Mae Suai', 46),
('เวียงป่าเป้า', 'Wiang Pa Pao', 46),
('พญาเม็งราย', 'Phaya Mengrai', 46),
('เวียงแก่น', 'Wiang Kaen', 46),
('ขุนตาล', 'Khun Tan', 46),
('แม่ฟ้าหลวง', 'Mae Fa Luang', 46),
('แม่ลาว', 'Mae Lao', 46),
('เวียงเชียงรุ้ง', 'Wiang Chiang Rung', 46),
('ดอยหลวง', 'Doi Luang', 46);
INSERT INTO masterdata_districts (title, title_en, province_id) VALUES
('เมืองแม่ฮ่องสอน', 'Mueang Mae Hong Son', 47),
('ขุนยวม', 'Khun Yuam', 47),
('ปาย', 'Pai', 47),
('แม่สะเรียง', 'Mae Sariang', 47),
('แม่ลาน้อย', 'Mae La Noi', 47),
('สบเมย', 'Sop Moei', 47),
('ปางมะผ้า', 'Pang Mapha', 47),
('เมืองนครสวรรค์', 'Mueang Nakhon Sawan', 48),
('โกรกพระ', 'Krok Phra', 48),
('ชุมแสง', 'Chum Saeng', 48),
('หนองบัว', 'Nong Bua', 48),
('บรรพตพิสัย', 'Banphot Phisai', 48),
('เก้าเลี้ยว', 'Kao Liao', 48),
('ตาคลี', 'Takhli', 48),
('ท่าตะโก', 'Tha Tako', 48),
('ไพศาลี', 'Phaisali', 48),
('พยุหะคีรี', 'Phayuha Hkiri', 48),
('ลาดยาว', 'Lat Yao', 48),
('ตากฟ้า', 'Tak Fa', 48),
('แม่วงก์', 'Mae Wong', 48),
('แม่เปิน', 'Mae Pern', 48),
('ชุมตาบง', 'Chum Ta Bong', 48),
('เมืองอุทัยธานี', 'Mueang Uthai Thani', 49),
('ทัพทัน', 'Thap Than', 49),
('สว่างอารมณ์', 'Sawang Arom', 49),
('หนองฉาง', 'Nong Chang', 49),
('หนองขาหย่าง', 'Nong Khayang', 49),
('บ้านไร่', 'Ban Rai', 49),
('ลานสัก', 'Lan Sak', 49),
('ห้วยคต', 'Huai Khot', 49),
('เมืองกำแพงเพชร', 'Mueang Kamphaeng Phet', 50),
('ไทรงาม', 'Sai Ngam', 50),
('คลองลาน', 'Khlong Lan', 50),
('ขาณุวรลักษบุรี', 'Khanu Woralaksaburi', 50),
('คลองขลุง', 'Khlong Khlung', 50),
('พรานกระต่าย', 'Phran Kratai', 50),
('ลานกระบือ', 'Lan Krabue', 50),
('ทรายทองวัฒนา', 'Sai Thong Watthana', 50),
('ปางศิลาทอง', 'Pang Sila Thong', 50),
('บึงสามัคคี', 'Bueng Samakkhi', 50),
('โกสัมพีนคร', 'Kosamphi Nakhon', 50),
('เมืองตาก', 'Mueang Tak', 51),
('บ้านตาก', 'Ban Tak', 51),
('สามเงา', 'Sam Ngao', 51),
('แม่ระมาด', 'Mae Ramat', 51),
('ท่าสองยาง', 'Tha Song Yang', 51),
('แม่สอด', 'Mae Sot', 51),
('พบพระ', 'Phop Phra', 51),
('อุ้มผาง', 'Um Phang', 51),
('วังเจ้า', 'Wang Chao', 51),
('เมืองสุโขทัย', 'Mueang Sukhothai', 52),
('บ้านด่านลานหอย', 'Ban Dan Lan Hoi', 52),
('คีรีมาศ', 'Khiri Mat', 52),
('กงไกรลาศ', 'Kong Krailat', 52),
('ศรีสัชนาลัย', 'Si Satchanalai', 52),
('ศรีสำโรง', 'Si Samrong', 52),
('สวรรคโลก', 'Sawankhalok', 52),
('ศรีนคร', 'Si Nakhon', 52),
('ทุ่งเสลี่ยม', 'Thung Saliam', 52),
('เมืองพิษณุโลก', 'Mueang Phitsanulok', 53),
('นครไทย', 'Nakhon Thai', 53),
('ชาติตระการ', 'Chat Trakan', 53),
('บางระกำ', 'Bang Rakam', 53),
('บางกระทุ่ม', 'Bang Krathum', 53),
('พรหมพิราม', 'Phrom Phiram', 53),
('วัดโบสถ์', 'Wat Bot', 53),
('วังทอง', 'Wang Thong', 53),
('เนินมะปราง', 'Noen Maprang', 53),
('เมืองพิจิตร', 'Mueang Phichit', 54),
('วังทรายพูน', 'Wang Sai Phun', 54),
('โพธิ์ประทับช้าง', 'Pho Prathap Chang', 54),
('ตะพานหิน', 'Taphan Hin', 54),
('บางมูลนาก', 'Bang Mun Nak', 54),
('โพทะเล', 'Pho Thale', 54),
('สามง่าม', 'Sam Ngam', 54),
('ทับคล้อ', 'Tap Khlo', 54),
('สากเหล็ก', 'Sak Lek', 54),
('บึงนาราง', 'Bueng Na Rang', 54),
('ดงเจริญ', 'Dong Charoen', 54),
('วชิรบารมี', 'Wachirabarami', 54),
('เมืองเพชรบูรณ์', 'Mueang Phetchabun', 55),
('ชนแดน', 'Chon Daen', 55),
('หล่มสัก', 'Lom Sak', 55),
('หล่มเก่า', 'Lom Kao', 55),
('วิเชียรบุรี', 'Wichian Buri', 55),
('ศรีเทพ', 'Si Thep', 55),
('หนองไผ่', 'Nong Phai', 55),
('บึงสามพัน', 'Bueng Sam Phan', 55),
('น้ำหนาว', 'Nam Nao', 55),
('วังโป่ง', 'Wang Pong', 55),
('เขาค้อ', 'Khao kho', 55),
('เมืองราชบุรี', 'Mueang Ratchaburi', 56),
('จอมบึง', 'Chom Bueng', 56),
('สวนผึ้ง', 'Suan Phueng', 56),
('ดำเนินสะดวก', 'Damnoen Saduak', 56),
('บ้านโป่ง', 'Ban Pong', 56),
('บางแพ', 'Bang Phae', 56),
('โพธาราม', 'Photharam', 56),
('ปากท่อ', 'Pak Tho', 56),
('วัดเพลง', 'Wat Phleng', 56),
('บ้านคา', 'Ban Kha', 56),
('เมืองกาญจนบุรี', 'Mueang Kanchanaburi', 57),
('ไทรโยค', 'Sai Yok', 57),
('บ่อพลอย', 'Bo Phloi', 57),
('ศรีสวัสดิ์', 'Si Sawat', 57),
('ท่ามะกา', 'Tha Maka', 57),
('ท่าม่วง', 'Tha Muang', 57),
('ทองผาภูมิ', 'Thong Pha Phum', 57),
('สังขละบุรี', 'Sangkhla Buri', 57),
('พนมทวน', 'Phanom Thuan', 57),
('เลาขวัญ', 'Lao Khwan', 57),
('ด่านมะขามเตี้ย', 'Dan Makham Tia', 57),
('หนองปรือ', 'Nong Prue', 57),
('ห้วยกระเจา', 'Huai Krachao', 57),
('เมืองสุพรรณบุรี', 'Mueang Saphan Buri', 58),
('เดิมบางนางบวช', 'Doem Bang Nang Buat', 58),
('ด่านช้าง', 'Dan Chang', 58),
('บางปลาม้า', 'Bang Pla Ma', 58),
('ศรีประจันต์', 'Si Prachan', 58),
('ดอนเจดีย์', 'Don Chedi', 58),
('สองพี่น้อง', 'Song Phi Nong', 58),
('สามชุก', 'Sam Chuk', 58),
('อู่ทอง', 'U Thong', 58),
('หนองหญ้าไซ', 'Nong Ya Sai', 58),
('เมืองนครปฐม', 'mueang Nakhon Pathom', 59),
('กำแพงแสน', 'Kamphaeng Saen', 59),
('นครชัยศรี', 'Nakhon Chai Si', 59),
('ดอนตูม', 'Don Tum', 59),
('บางเลน', 'Bang Len', 59),
('สามพราน', 'Sam Phran', 59),
('พุทธมณฑล', 'Phutthamonthon', 59),
('เมืองสมุทรสาคร', 'Mueang Samut Sakhon', 60),
('กระทุ่มแบน', 'Krathum Baen', 60),
('บ้านแพ้ว', 'Ban Phaeo', 60),
('เมืองสมุทรสงคราม', 'Mueang Samut Songkhram', 61),
('บางคนที', 'Bang Khonthi', 61),
('อัมพวา', 'Amphawa', 61),
('เมืองเพชรบุรี', 'Mueang Phetchaburi', 62),
('เขาย้อย', 'Khao Yoi', 62),
('หนองหญ้าปล้อง', 'Nong Ya Plong', 62),
('ชะอำ', 'Cha-am', 62),
('ท่ายาง', 'Tha Yang', 62),
('บ้านลาด', 'Ban Lat', 62),
('บ้านแหลม', 'Ban Laem', 62),
('แก่งกระจาน', 'Kaeng Krachan', 62),
('เมืองประจวบคีรีขันธ์', 'Mueang Prachuap Khiri Khan', 63),
('กุยบุรี', 'Kui Buri', 63),
('ทับสะแก', 'Thap Sakae', 63),
('บางสะพาน', 'Bang Saphan', 63),
('บางสะพานน้อย', 'Bang Saphan Noi', 63),
('ปราณบุรี', 'Pran Buri', 63),
('หัวหิน', 'Hua Hin', 63),
('สามร้อยยอด', 'Sam Roi Yot', 63),
('เมืองนครศรีธรรมราช', 'Mueang Nakhon Si Thammarat', 64),
('พรหมคีรี', 'Phrom Khiri', 64),
('ลานสกา', 'Lan Saka', 64),
('ฉวาง', 'Chawang', 64),
('พิปูน', 'Phipun', 64),
('เชียรใหญ่', 'Chian Yai', 64),
('ชะอวด', 'Cha-uat', 64),
('ท่าศาลา', 'Tha Sala', 64),
('ทุ่งสง', 'Thung Song', 64),
('นาบอน', 'Na Bon', 64),
('ทุ่งใหญ่', 'Thung Yai', 64),
('ปากพนัง', 'Pak Phanang', 64),
('ร่อนพิบูลย์', 'Ron Phibun', 64),
('สิชล', 'Sichon', 64),
('ขนอม', 'Khanom', 64),
('หัวไทร', 'Hua Sai', 64),
('บางขัน', 'Bang Khan', 64),
('ถ้ำพรรณรา', 'Tham Phannara', 64),
('จุฬาภรณ์', 'Chulabhorn', 64),
('พระพรหม', 'Phra Phrom', 64),
('นบพิตำ', 'Nopphitam', 64),
('ช้างกลาง', 'Chang Klang', 64),
('เฉลิมพระเกียรติ', 'Chaloem Phra Kiet', 64),
('เมืองกระบี่', 'Mueang Krabi', 65),
('เขาพนม', 'Khao Phanom', 65),
('เกาะลันตา', 'Ko Lanta', 65),
('คลองท่อม', 'Khlong Thom', 65),
('อ่าวลึก', 'Ao Luek', 65),
('ปลายพระยา', 'Plai Phraya', 65),
('ลำทับ', 'Lam Thap', 65),
('เหนือคลอง', 'Nuea Khlong', 65),
('เมืองพังงา', 'Mueang Phang-nga', 66),
('เกาะยาว', 'Ko Yao', 66),
('กะปง', 'Kapong', 66),
('ตะกั่วทุ่ง', 'Takua Thung', 66),
('ตะกั่วป่า', 'Takua Pa', 66),
('คุระบุรี', 'Khura Buri', 66),
('ทับปุด', 'Thap Put', 66),
('ท้ายเหมือง', 'Thai Mueang', 66),
('เมืองภูเก็ต', 'Mueang Phuket', 67),
('กะทู้', 'Kathu', 67),
('ถลาง', 'Thalang', 67),
('เมืองสุราษฎร์ธานี', 'Mueang Surat Thani', 68),
('กาญจนดิษฐ์', 'Kanchanadit', 68),
('ดอนสัก', 'Don Sak', 68),
('เกาะสมุย', 'Ko Samui', 68),
('เกาะพะงัน', 'Ko Pha-ngan', 68),
('ไชยา', 'Chaiya', 68),
('ท่าชนะ', 'Tha Chana', 68),
('คีรีรัฐนิคม', 'Khiri Rat Nikhom', 68),
('บ้านตาขุน', 'Ban Ta Khun', 68),
('พนม', 'Phanom', 68),
('ท่าฉาง', 'Tha Chang', 68),
('บ้านนาสาร', 'Ban Na San', 68),
('บ้านนาเดิม', 'Ban Na Doem', 68),
('เคียนซา', 'Khian Sa', 68),
('เวียงสระ', 'Wiang Sa', 68),
('พระแสง', 'Phrasaeng', 68),
('พุนพิน', 'Phunphin', 68),
('ชัยบุรี', 'Chai Buri', 68),
('วิภาวดี', 'Chai Buri', 68),
('เมืองระนอง', 'Mueang Ranong', 69),
('ละอุ่น', 'La-un', 69),
('กะเปอร์', 'Papoe', 69),
('กระบุรี', 'Kra Buri', 69),
('สุขสำราญ', 'Suk Samran', 69),
('เมืองชุมพร', 'Mueang Chumphon', 70),
('ท่าแซะ', 'Tha Sae', 70),
('ปะทิว', 'Pathio', 70),
('หลังสวน', 'Lang Suan', 70),
('ละแม', 'Lamae', 70),
('พะโต๊ะ', 'Phato', 70),
('สวี', 'Sawi', 70),
('ทุ่งตะโก', 'Thung Tako', 70),
('เมืองสงขลา', 'Muaeng Songkhla', 71),
('สทิงพระ', 'Sathing Phra', 71),
('จะนะ', 'Chana', 71),
('นาทวี', 'Na Thawi', 71),
('เทพา', 'Thepha', 71),
('สะบ้าย้อย', 'Saba Yoi', 71),
('ระโนด', 'Ranot', 71),
('กระแสสินธุ์', 'Krasae Sin', 71),
('รัตภูมิ', 'Rattaphum', 71),
('สะเดา', 'Sadao', 71),
('หาดใหญ่', 'Hat Yai', 71),
('นาหม่อม', 'Na Mom', 71),
('ควนเนียง', 'Khuan Niang', 71),
('บางกล่ำ', 'Bang Klam', 71),
('สิงหนคร', 'Singhanakhon', 71),
('คลองหอยโข่ง', 'Khlong Hoi Khong', 71),
('เมืองสตูล', 'Mueang Satun', 72),
('ควนโดน', 'Khuan Don', 72),
('ควนกาหลง', 'Khuan Kalong', 72),
('ท่าแพ', 'Tha Phae', 72),
('ละงู', 'La-ngu', 72),
('ทุ่งหว้า', 'Thung  Wa', 72),
('มะนัง', 'Manang', 72),
('เมืองตรัง', 'Mueang Trang', 73),
('กันตัง', 'Kantang', 73),
('ย่านตาขาว', 'Yan Ta Khao', 73),
('ปะเหลียน', 'Palian', 73),
('สิเกา', 'Sikao', 73),
('ห้วยยอด', 'Huai Yot', 73),
('วังวิเศษ', 'Wang Wiset', 73),
('นาโยง', 'Na Yong', 73),
('รัษฎา', 'Ratsada', 73),
('หาดสำราญ', 'Hat Samran', 73),
('เมืองพัทลุง', 'Mueang Phatthalung', 74),
('กงหรา', 'Kong Ra', 74),
('เขาชัยสน', 'Khao Chaison', 74),
('ตะโหมด', 'Tamot', 74),
('ควนขนุน', 'Khuan Khanun', 74),
('ปากพะยูน', 'Pak Phayun', 74),
('ศรีบรรพต', 'Si Banphot', 74),
('ป่าบอน', 'Pa Bon', 74),
('บางแก้ว', 'Bang Kaeo', 74),
('ป่าพยอม', 'Pa Phayom', 74),
('ศรีนครินทร์', 'Srinagarindra', 74),
('เมืองปัตตานี', 'Mueang Pattani', 75),
('โคกโพธิ์', 'Khok Pho', 75),
('หนองจิก', 'Nong Chik', 75),
('ปะนาเระ', 'Panare', 75),
('มายอ', 'Mayo', 75),
('ทุ่งยางแดง', 'Thung Yang Daeng', 75),
('สายบุรี', 'Sai Buri', 75),
('ไม้แก่น', 'Mai Kaen', 75),
('ยะหริ่ง', 'Yaring', 75),
('ยะรัง', 'Yarang', 75),
('กะพ้อ', 'Kapho', 75),
('แม่ลาน', 'Mae Lan', 75),
('เมืองยะลา', 'Mueang Yala', 76),
('เบตง', 'Betong', 76),
('บันนังสตา', 'Bannang Sata', 76),
('ธารโต', 'Than To', 76),
('ยะหา', 'Yaha', 76),
('รามัน', 'Raman', 76),
('กาบัง', 'Kabang', 76),
('กรงปีนัง', 'Krong Pinang', 76),
('เมืองนราธิวาส', 'Mueang Narathiwat', 77),
('ตากใบ', 'Tak Bai', 77),
('บาเจาะ', 'Tak Bai', 77),
('ยี่งอ', 'Yi-ngo', 77),
('ระแงะ', 'Ra-ngae', 77),
('รือเสาะ', 'Rueso', 77),
('ศรีสาคร', 'Si Sakhon', 77),
('แว้ง', 'Waeng', 77),
('สุคิริน', 'Sukhirin', 77),
('สุไหงโก-ลก', 'Su-ngai Kolok', 77),
('สุไหงปาดี', 'Su-ngai Padi', 77),
('จะแนะ', 'Chanae', 77),
('เจาะไอร้อง', 'Cho-airong', 77);